DEBUG    root:logger.py:11 Debug message
INFO     root:logger.py:12 Information regarding the test case
WARNING  root:logger.py:13 Test case pass but with a Warning message
ERROR    root:logger.py:14 Test case fail
CRITICAL root:logger.py:15 Important test case fail on which other test case depends
INFO     root:test_DeleteRequest.py:12 Starting test_Delete_request
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): reqres.in:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://reqres.in:443 "DELETE /api/users/2 HTTP/1.1" 204 0
INFO     root:test_DeleteRequest.py:22 Ending test_Delete_request