[35mDEBUG   [0m root:logger.py:11 Debug message
[32mINFO    [0m root:logger.py:12 Information regarding the test case
[33mWARNING [0m root:logger.py:13 Test case pass but with a Warning message
[31m[1mERROR   [0m root:logger.py:14 Test case fail
[31mCRITICAL[0m root:logger.py:15 Important test case fail on which other test case depends
[32mINFO    [0m root:test_PostRequest.py:62 Starting test_post_request_login
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): reqres.in:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://reqres.in:443 "POST /api/login HTTP/1.1" 200 None
[32mINFO    [0m root:test_PostRequest.py:82 Ending test_post_request