DEBUG    root:logger.py:44 Debug message
INFO     root:logger.py:45 Information regarding the test case
WARNING  root:logger.py:46 Test case pass but with a Warning message
ERROR    root:logger.py:47 Test case fail
CRITICAL root:logger.py:48 Important test case fail on which other test case depends
INFO     root:test_PostRequest.py:12 Starting test_post_request_create
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): reqres.in:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://reqres.in:443 "POST /api/users HTTP/1.1" 201 84